select*
from dim_customers;

-- DATA EXPLORATION 

-- Explore all objects in the database

select*
from information_schema.tables
where table_schema = 'datawarehouseanalytics';

-- Explore all columns in the database

select *
from  information_schema.columns 
where table_schema = 'datawarehouseanalytics'
and table_name = 'dim_customers'
order by ordinal_position;

-- DIMENSIONS EXPLORATION

-- Explore all countries our customers comes from

Select distinct country
from dim_customers;

-- Explore all categories of products

select distinct category, subcategory, product_name, row_number() over(order by category) as row_num
from dim_products;

-- DATE EXPLORATION

-- date of the first order and the last order
-- How many years of sales are available

select  min(order_date) as first_date, 
max(order_date) as last_date,
datediff(max(order_date),min(order_date)), 
timestampdiff(year, min(order_date), max(order_date))
from fact_sales;

-- Find the youngest and the oldest customer

update dim_customers
set birthdate = null
where trim(birthdate) = '';

select 
min(birthdate) as oldest,
max(birthdate) as youngest,
timestampdiff(year, min(birthdate), curdate()) as oldest_age,
timestampdiff(year, max(birthdate), curdate()) as youngest_age
from dim_customers
where 'bithdate' is not null; 

-- MEASURES EXPLORATION

-- Calculate the key metrics of the business
-- Total sales, how many items are sold, avg selling price, total no of orders, total no of products, total no of customers that has placed an order

select 
sum(sales_amount) as total_sales,
sum(quantity) as total_quantity, 
round(avg(sales_amount)) as avg_sales, 
count(distinct order_number) as total_orders,
count(distinct customer_key) as total_customers
from fact_Sales;

select count(product_id) as total_products
from dim_products;

select*
from fact_sales;

-- Generate a report that shows all key metrics of the business

select 'Total Sales' as measure_name, sum(sales_amount) as measure_value from fact_sales
union all
select 'Total Quantity Sold' as measure_name, sum(quantity) as measure_value from fact_sales
union all
select 'Average Sales' as measure_name, round(avg(sales_amount)) as measure_value from fact_sales
union all
select 'Total Orders' as measure_name, count(distinct order_number) as measure_value from fact_sales
union all
select 'Total Customers' as measure_name, count(distinct customer_key) as measure_value from fact_sales
union all
select 'Total Products' as measure_name, count(product_id) as measure_value from dim_products;   

-- MAGNITUDE ANALYSIS (Measure by Dimension)

-- Total Sales by Country

select country, sum(sales_amount) as total_sales
from fact_sales s1
left join dim_customers c1
	on s1.customer_key = c1.customer_key
group by country
order by 2 desc;

-- Total Customers by Countries

select country, count(customer_key) as total_customers
from dim_customers
group by country
order by 2 desc;

-- Find total customers by gender

select gender, count(customer_key)
from dim_customers
group by gender
order by 2 desc;

-- Find total products by category

select category, count(product_key)
from dim_products
group by category
order by 2 desc;

-- What is the average cost in each category

select category, round(avg(cost))
from dim_products
group by category
order by 2 desc;

-- Total revenue generated from each category

select category, 
sum(sales_amount) as total_revenue
from fact_sales p1
join dim_products s1
	on p1.product_key = s1.product_key
group by category
order by 2 desc;

-- Total revenue generated by each customer

select c1.customer_key, first_name, last_name, sum(sales_amount) as Revenue
from fact_sales s1
join dim_customers c1
	on s1.customer_key = c1.customer_key
group by c1.customer_key, first_name, last_name
order by 4 desc;

-- RANKING

-- Which 5 products generate the highest revenue

with ranking_cte as 
(select product_name,
sum(sales_amount) as total_revenue, 
dense_rank() over(order by sum(sales_amount) desc)  as ranking
from dim_products d1
join fact_sales s1
	on d1.product_key = s1.product_key
group by product_name)
select *
from ranking_cte
where ranking <=5;

-- Which 5 products generate the lowest sales
    
select *
from
(select product_name,
sum(sales_amount) as total_revenue, 
dense_rank() over(order by sum(sales_amount))  as ranking
from dim_products d1
join fact_sales s1
	on d1.product_key = s1.product_key
group by product_name) sub
where ranking <= 5;